const imagePool = Array.from({ length: 24 }, (_, i) => `assets/images/dish-${String(i + 1).padStart(2, "0")}.webp`);
const logoImage = "assets/images/logo.png";

const lunchMenu = [
  { id: "B1-K", code: "B1", name: "Bratnudeln mit Gemüse und Ei", description: "Klein", price: 5.0, allergens: "5, 7, C", tags: ["vegetarisch"], image: logoImage },
  { id: "B1-G", code: "B1", name: "Bratnudeln mit Gemüse und Ei", description: "Groß", price: 6.0, allergens: "5, 7, C", tags: ["vegetarisch"], image: logoImage },
  { id: "B1-M", code: "B1", name: "Bratnudeln mit Gemüse und Ei", description: "Mega", price: 7.9, allergens: "5, 7, C", tags: ["vegetarisch"], image: logoImage },
  { id: "B2-K", code: "B2", name: "Bratnudeln mit Hühnerfleisch und Ei", description: "Klein", price: 5.5, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "B2-G", code: "B2", name: "Bratnudeln mit Hühnerfleisch und Ei", description: "Groß", price: 6.5, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "B2-M", code: "B2", name: "Bratnudeln mit Hühnerfleisch und Ei", description: "Mega", price: 8.9, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "B3-K", code: "B3", name: "Bratreis mit Gemüse und Ei", description: "Klein", price: 5.0, allergens: "5, 7, C", tags: ["vegetarisch"], image: logoImage },
  { id: "B3-G", code: "B3", name: "Bratreis mit Gemüse und Ei", description: "Groß", price: 6.0, allergens: "5, 7, C", tags: ["vegetarisch"], image: logoImage },
  { id: "B3-M", code: "B3", name: "Bratreis mit Gemüse und Ei", description: "Mega", price: 7.9, allergens: "5, 7, C", tags: ["vegetarisch"], image: logoImage },
  { id: "B4-K", code: "B4", name: "Bratreis mit Hühnerfleisch und Ei", description: "Klein", price: 5.5, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "B4-G", code: "B4", name: "Bratreis mit Hühnerfleisch und Ei", description: "Groß", price: 6.5, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "B4-M", code: "B4", name: "Bratreis mit Hühnerfleisch und Ei", description: "Mega", price: 8.9, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "B5-K", code: "B5", name: "Bratnudeln mit knusprigem Hähnchenstück", description: "Klein", price: 5.5, allergens: "5, A1, C, K", tags: ["beliebt"], image: logoImage },
  { id: "B5-G", code: "B5", name: "Bratnudeln mit knusprigem Hähnchenstück", description: "Groß", price: 6.5, allergens: "5, A1, C, K", tags: ["beliebt"], image: logoImage },
  { id: "B5-M", code: "B5", name: "Bratnudeln mit knusprigem Hähnchenstück", description: "Mega", price: 11.9, allergens: "5, A1, C, K", tags: ["beliebt"], image: logoImage },
  { id: "B6", code: "B6", name: "Bratnudeln mit knuspriger Ente", description: "Groß", price: 14.5, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "B8", code: "B8", name: "Bratnudeln mit Minifrühlingsrolle", description: "Mittagsgericht", price: 6.5, allergens: "5, 7, C", tags: ["vegetarisch"], image: logoImage },
  { id: "B9", code: "B9", name: "Chickenstreifen mit Reis, süß-sauer", description: "Mittagsgericht", price: 6.5, allergens: "5, 7, A1", tags: ["beliebt"], image: logoImage },
  { id: "B10", code: "B10", name: "Gemüse Chop Suey mit Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, F", tags: ["vegetarisch", "vegan"], image: logoImage },
  { id: "B11", code: "B11", name: "Gemüse Chop Suey mit Hühnerfleisch und Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, F", tags: [], image: logoImage },
  { id: "B12", code: "B12", name: "Erdnuss-Sauce mit Gemüse und Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, E, G", tags: ["vegetarisch"], image: logoImage },
  { id: "B13", code: "B13", name: "Erdnuss-Sauce mit Hühnerfleisch, Gemüse und Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, E, G", tags: [], image: logoImage },
  { id: "B14", code: "B14", name: "Red-Curry mit Gemüse und Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, G", tags: ["vegetarisch", "scharf"], image: logoImage },
  { id: "B15", code: "B15", name: "Red-Curry mit Hühnerfleisch, Gemüse und Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, G", tags: ["scharf"], image: logoImage },
  { id: "B16", code: "B16", name: "Mango mit Gemüse und Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, G", tags: ["vegetarisch"], image: logoImage },
  { id: "B17", code: "B17", name: "Mango mit Hühnerfleisch, Gemüse und Reis", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, G", tags: [], image: logoImage },
  { id: "B20", code: "B20", name: "Minifrühlingsrollen, 10 Stk. vegetarisch", description: "Mittagsgericht", price: 4.5, allergens: "5, 7, A1", tags: ["vegetarisch"], image: logoImage },
  { id: "B21", code: "B21", name: "Sommerrolle mit BIO Tofu, Hoisin Sauce", description: "Mittagsgericht", price: 7.5, allergens: "5, 7, D, F", tags: ["vegetarisch"], image: imagePool[21] },
  { id: "B23", code: "B23", name: "Sommerrolle mit Garnelen und Hoisin Sauce", description: "Mittagsgericht", price: 8.5, allergens: "5, 7, B, D", tags: [], image: imagePool[19] }
];

const dinnerMenu = [
  { id: "1", code: "1", category: "Suppen", name: "Peking Suppe", description: "Entenfleisch, Gemüse und Ei.", price: 5.0, allergens: "5, 7, C", tags: ["beliebt"], image: logoImage },
  { id: "2", code: "2", category: "Suppen", name: "Thai Suppe", description: "Garnelen, Hähnchen und Gemüse.", price: 5.9, allergens: "5, 7, B", tags: ["scharf"], image: logoImage },
  { id: "3", code: "3", category: "Suppen", name: "Sake Miso", description: "Misosuppe mit Lachs, Seetang und Pilzen.", price: 6.5, allergens: "5, 7, D", tags: [], image: logoImage },
  { id: "4", code: "4", category: "Vorspeisen", name: "Nem", description: "Vietnamesische Frühlingsrollen mit Hühnerfleisch, Glasnudeln und Gemüse.", price: 6.0, allergens: "A1, B, C, G", tags: ["beliebt"], image: logoImage },
  { id: "5", code: "5", category: "Vorspeisen", name: "Minifrühlingsrolle", description: "Mini-Frühlingsrollen mit Gemüsefüllung.", price: 5.0, allergens: "5, 7, C, D, F", tags: ["vegetarisch"], image: logoImage },
  { id: "6", code: "6", category: "Vorspeisen", name: "Tempura Ebi", description: "Knusprige Riesengarnelen im Tempurateig, serviert mit Mayonnaise.", price: 6.5, allergens: "5, 7, A1", tags: ["beliebt"], image: imagePool[6] },
  { id: "7", code: "7", category: "Vorspeisen", name: "Edamame", description: "Gedämpfte Sojabohnen mit Meersalz.", price: 5.0, allergens: "F", tags: ["vegetarisch", "vegan"], image: logoImage },
  { id: "8", code: "8", category: "Vorspeisen", name: "Kimchi", description: "Eingelegter Chinakohl nach koreanischer Art.", price: 4.5, allergens: "7", tags: ["vegetarisch", "scharf"], image: logoImage },
  { id: "9", code: "9", category: "Vorspeisen", name: "Seetang", description: "Japanischer Wakame-Seetangsalat mit Sesam.", price: 5.0, allergens: "K", tags: ["vegetarisch", "vegan"], image: logoImage },
  { id: "10", code: "10", category: "Vorspeisen", name: "Gyoza Vegetarisch", description: "Gebratene japanische Teigtaschen mit Ponzu-Sauce.", price: 6.9, allergens: "5, 7, F, K", tags: ["vegetarisch"], image: imagePool[16] },
  { id: "11", code: "11", category: "Vorspeisen", name: "Gyoza Hühnerfleisch", description: "Gebratene japanische Teigtaschen mit Ponzu-Sauce.", price: 6.9, allergens: "7", tags: [], image: imagePool[16] },
  { id: "12", code: "12", category: "Vorspeisen", name: "Sommerrolle Tofu", description: "Mit Salat, Gemüse, Kräutern, Erdnüssen und Hoisin-Dip.", price: 6.9, allergens: "E, F", tags: ["vegetarisch"], image: imagePool[21] },
  { id: "13", code: "13", category: "Vorspeisen", name: "Sommerrolle Garnelen", description: "Mit Salat, Gemüse, Kräutern, Erdnüssen und Hoisin-Dip.", price: 7.5, allergens: "7, B, E", tags: [], image: imagePool[19] },
  { id: "14", code: "14", category: "Vorspeisen", name: "Maiwok Tapas Mix", description: "Platte mit Vorspeisen, Grill-Spezialitäten und Salat für 2 Personen.", price: 19.0, allergens: "5, 7, C, D, E", tags: ["beliebt"], image: imagePool[18] },
  { id: "15", code: "15", category: "Salate", name: "Garnelen-Mango", description: "Aromatischer Salat mit Mango, Garnelen, Kräutern, Zwiebeln und Limetten-Chili-Dressing.", price: 13.9, allergens: "5, 7, B, E", tags: ["scharf"], image: imagePool[20] },
  { id: "16", code: "16", category: "Salate", name: "Avocado-Tempura-Chicken", description: "Grüner Salat mit Avocado, Tempura Chicken, Chili, Koriander, Erdnüssen und Sesamsoße.", price: 11.9, allergens: "5, 7, C, E", tags: ["beliebt"], image: imagePool[8] },
  { id: "20", code: "20", category: "Bowls", name: "Bowl Lachs", description: "Sushireis, Lachs, Seetang, Rucola, Kimchi, Avocado, Erdnüsse, Sesam und Teriyakisauce.", price: 15.9, allergens: "7, D", tags: ["beliebt"], image: logoImage },
  { id: "21", code: "21", category: "Bowls", name: "Bowl Udon", description: "Grüner Salat, Avocado, Tempura Chicken, Chili, Koriander und Erdnüsse mit Sesamsoße.", price: 13.9, allergens: "5, 7, C, K", tags: [], image: imagePool[8] },
  { id: "25", code: "25", category: "Hauptspeisen", name: "Bun Tofu", description: "Reisnudeln mit Salat, Kräutern, Erdnüssen und hausgemachter Fischsauce.", price: 13.9, allergens: "F", tags: ["vegetarisch"], image: logoImage },
  { id: "26", code: "26", category: "Hauptspeisen", name: "Bun Vit", description: "Reisnudeln mit knuspriger Ente, Salat, Kräutern und Erdnüssen.", price: 14.9, allergens: "5, 7, D, E", tags: ["beliebt"], image: logoImage },
  { id: "27", code: "27", category: "Hauptspeisen", name: "Bun Nem-Bo", description: "Reisnudeln mit Rindfleisch und hausgemachten vietnamesischen Frühlingsrollen.", price: 14.9, allergens: "5, 7, E", tags: [], image: logoImage },
  { id: "30", code: "30", category: "Nudelgerichte", name: "Pad Thai Tom", description: "Gebratene Reisbandnudeln mit Garnelen, Pak Choi, Paprika und Möhren nach Pad-Thai-Art.", price: 15.9, allergens: "5, 7, B, E", tags: ["scharf"], image: imagePool[7] },
  { id: "31", code: "31", category: "Nudelgerichte", name: "Udon", description: "Gebratene Udon-Nudeln mit Pak Choi, Paprika, Tempura Chicken und Teriyaki-Soße.", price: 13.9, allergens: "5, 7, C, E", tags: ["beliebt"], image: logoImage },
  { id: "35", code: "35", category: "Suppen", name: "Pho Tofu", description: "Aromatische Brühe mit Reisbandnudeln, Frühlingszwiebeln, Koriander und Kräutern.", price: 13.9, allergens: "F", tags: ["vegetarisch"], image: logoImage },
  { id: "36", code: "36", category: "Suppen", name: "Pho Rindfleisch", description: "Aromatische Brühe mit Rindfleisch, Reisbandnudeln, Frühlingszwiebeln und Kräutern.", price: 14.9, allergens: "5, 7", tags: ["beliebt"], image: logoImage },
  { id: "37", code: "37", category: "Suppen", name: "Pho Spezial", description: "Mit Garnelen, Rind und Hühnerfleisch.", price: 16.9, allergens: "5, 7, B", tags: ["beliebt"], image: logoImage },
  { id: "40", code: "40", category: "Suppen", name: "Udon Nudelsuppe", description: "Mit Riesengarnelen, Lachs, Pak Choi, Karotten und Paprika.", price: 16.9, allergens: "B, D", tags: [], image: logoImage },
  { id: "45", code: "45", category: "Reisgerichte", name: "Gebratener Jasminreis mit knuspriger Ente", description: "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei.", price: 15.5, allergens: "5, 7, C, F", tags: ["beliebt"], image: logoImage },
  { id: "46", code: "46", category: "Reisgerichte", name: "Gebratener Jasminreis mit Garnelen", description: "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei.", price: 15.9, allergens: "5, 7, B, C, F", tags: [], image: logoImage },
  { id: "50", code: "50", category: "Nudelgerichte", name: "Gebratene Nudeln mit paniertem Hühnerfleisch", description: "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei.", price: 13.9, allergens: "5, 7, A1, C, F", tags: [], image: logoImage },
  { id: "51", code: "51", category: "Nudelgerichte", name: "Gebratene Nudeln mit geröstetem Chicken", description: "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei.", price: 14.5, allergens: "5, 7, C, F", tags: ["beliebt"], image: logoImage },
  { id: "52", code: "52", category: "Nudelgerichte", name: "Gebratene Nudeln mit knuspriger Ente", description: "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei.", price: 15.5, allergens: "5, 7, C, F", tags: ["beliebt"], image: logoImage },
  { id: "53", code: "53", category: "Nudelgerichte", name: "Gebratene Nudeln mit Riesengarnelen", description: "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei.", price: 15.5, allergens: "5, 7, B, C, F", tags: [], image: logoImage },
  { id: "60", code: "60", category: "Gourmet", name: "Hühnerfleisch mit Sauce nach Wahl", description: "Mit gedämpftem Jasminreis, gebratenem Gemüse und Sauce nach Wahl.", price: 13.9, allergens: "5, 7", tags: [], image: logoImage },
  { id: "61", code: "61", category: "Gourmet", name: "Paniertes Hühnerfleisch mit Sauce nach Wahl", description: "Basilikum-Sojasauce, Mango-Sauce, Erdnusssauce oder rotes Thai-Curry.", price: 14.5, allergens: "5, 7, A1", tags: [], image: logoImage },
  { id: "62", code: "62", category: "Gourmet", name: "Geröstetes Chicken mit Sauce nach Wahl", description: "Mit gedämpftem Jasminreis, gebratenem Gemüse und Sauce nach Wahl.", price: 14.9, allergens: "5, 7, A1", tags: ["beliebt"], image: logoImage },
  { id: "63", code: "63", category: "Gourmet", name: "Knusprige Ente mit Sauce nach Wahl", description: "Mit gedämpftem Jasminreis, gebratenem Gemüse und Sauce nach Wahl.", price: 15.5, allergens: "5, 7", tags: ["beliebt"], image: logoImage },
  { id: "64", code: "64", category: "Gourmet", name: "Rindfleisch mit Sauce nach Wahl", description: "Mit gedämpftem Jasminreis, gebratenem Gemüse und Sauce nach Wahl.", price: 14.9, allergens: "5, 7", tags: [], image: logoImage },
  { id: "65", code: "65", category: "Gourmet", name: "Garnelen mit Sauce nach Wahl", description: "Mit gedämpftem Jasminreis, gebratenem Gemüse und Sauce nach Wahl.", price: 15.9, allergens: "5, 7, B, F", tags: [], image: logoImage },
  { id: "66", code: "66", category: "Gourmet", name: "Lachs mit Sauce nach Wahl", description: "Mit gedämpftem Jasminreis, gebratenem Gemüse und Sauce nach Wahl.", price: 16.9, allergens: "D", tags: [], image: logoImage },
  { id: "67", code: "67", category: "Gourmet", name: "Tofu mit Sauce nach Wahl", description: "Mit gedämpftem Jasminreis, gebratenem Gemüse und Sauce nach Wahl.", price: 13.5, allergens: "F", tags: ["vegetarisch", "vegan"], image: logoImage },
  { id: "70", code: "70", category: "Spezialgerichte", name: "Knusprige Ente BBQ Sosse", description: "Mit gedämpftem Jasminreis und Saisongemüse.", price: 16.9, allergens: "5, 7, B, F", tags: ["beliebt"], image: logoImage },
  { id: "71", code: "71", category: "Spezialgerichte", name: "Lachs BBQ Sosse", description: "Mit gedämpftem Jasminreis und Saisongemüse.", price: 17.9, allergens: "D", tags: [], image: logoImage },
  { id: "72", code: "72", category: "Spezialgerichte", name: "Knusprige Ente Knoblauchbutter Sosse", description: "Mit gedämpftem Jasminreis und Saisongemüse.", price: 16.9, allergens: "5, 7, B, G, F", tags: [], image: logoImage },
  { id: "73", code: "73", category: "Spezialgerichte", name: "Garnelen Knoblauchbutter Sosse", description: "Mit gedämpftem Jasminreis und Saisongemüse.", price: 17.9, allergens: "5, 7, B, G, F", tags: [], image: logoImage },
  { id: "100", code: "100", category: "Sushi", name: "Avocado Nigiri", description: "2 Stück Avocado.", price: 4.9, allergens: "", tags: ["vegetarisch"], image: logoImage },
  { id: "101", code: "101", category: "Sushi", name: "Sake Nigiri", description: "2 Stück schottischer Lachs.", price: 5.5, allergens: "D", tags: [], image: logoImage },
  { id: "102", code: "102", category: "Sushi", name: "Maguro Nigiri", description: "2 Stück Thunfisch.", price: 6.5, allergens: "D", tags: [], image: logoImage },
  { id: "103", code: "103", category: "Sushi", name: "Ebi Nigiri", description: "2 Stück Garnelen.", price: 5.5, allergens: "B", tags: [], image: logoImage },
  { id: "105", code: "105", category: "Sushi", name: "Avocado Maki", description: "6 Stück Avocado Maki.", price: 5.8, allergens: "", tags: ["vegetarisch"], image: logoImage },
  { id: "106", code: "106", category: "Sushi", name: "Kappa Maki", description: "6 Stück Gurke.", price: 5.5, allergens: "", tags: ["vegetarisch"], image: logoImage },
  { id: "107", code: "107", category: "Sushi", name: "Sake Maki", description: "6 Stück schottischer Lachs.", price: 5.9, allergens: "D", tags: [], image: logoImage },
  { id: "108", code: "108", category: "Sushi", name: "Tekka Maki", description: "6 Stück Thunfisch.", price: 6.9, allergens: "D", tags: [], image: logoImage },
  { id: "109", code: "109", category: "Sushi", name: "Ebi Maki", description: "6 Stück Ebi.", price: 5.9, allergens: "B", tags: [], image: logoImage },
  { id: "110", code: "110", category: "Sushi", name: "Veggie Freshness", description: "Avocado, Gurke, Mango, Frischkäse, Rucola und Sesam.", price: 9.9, allergens: "C, K", tags: ["vegetarisch"], image: logoImage },
  { id: "112", code: "112", category: "Sushi", name: "Schwarzwald Gockel", description: "Tempura Chicken, Gurken, Frischkäse, Rucola und Sesam.", price: 10.9, allergens: "5, 7, C, K", tags: ["beliebt"], image: logoImage },
  { id: "116", code: "116", category: "Sushi", name: "Smoky Salmon Shrimp", description: "Tempura Ebi, Gurken, Frischkäse, flambierter Lachs und Kaviar.", price: 15.5, allergens: "B, C, D", tags: ["beliebt"], image: logoImage },
  { id: "120", code: "120", category: "Sushi", name: "Crunchy Buddha", description: "Tempura Roll mit Avocado und Gurke, 6 Stück.", price: 6.9, allergens: "A1", tags: ["vegetarisch"], image: logoImage },
  { id: "121", code: "121", category: "Sushi", name: "Salmon Crunch", description: "Tempura Roll mit Lachs, 6 Stück.", price: 8.5, allergens: "A1, D", tags: [], image: logoImage },
  { id: "130", code: "130", category: "Sushi", name: "Mega Veggie", description: "Avocado, Gurke, Mango, Paprika, Rucola und Frischkäse.", price: 11.0, allergens: "A1, C", tags: ["vegetarisch"], image: logoImage },
  { id: "131", code: "131", category: "Sushi", name: "Mega Chicken Crunch", description: "Chicken, Gurke, Mango und Chilichicken.", price: 12.0, allergens: "5, 7, A1", tags: ["scharf"], image: logoImage },
  { id: "150", code: "150", category: "Sushi Menüs", name: "Veg Sushi Menü", description: "8 Inside-Out Avocado, Gurke, Mango, Frischkäse, Rucola, Sesam und 6 Maki Gurke.", price: 14.5, allergens: "C, K", tags: ["vegetarisch"], image: logoImage },
  { id: "151", code: "151", category: "Sushi Menüs", name: "Ohayo", description: "2 Nigiri und 6 Tempura Futo mit Lachs, Avocado, Gurken, Paprika, Frischkäse und Rucola.", price: 18.5, allergens: "A1, C, D", tags: ["beliebt"], image: logoImage },
  { id: "152", code: "152", category: "Sushi Menüs", name: "Minako", description: "6 Maki Sake, 2 Nigiri und 8 Inside-Out Surimi, Avocado, Frischkäse und Kaviar.", price: 19.9, allergens: "B, C, D", tags: [], image: logoImage },
  { id: "155", code: "155", category: "Kinder Menü", name: "Dino Nudeln", description: "Gebratene Nudeln mit Gemüse und Ei.", price: 8.9, allergens: "5, 7, C, F", tags: [], image: logoImage },
  { id: "156", code: "156", category: "Kinder Menü", name: "Kleine Tiger Bites", description: "Knuspriges Hähnchenstück mit gedämpftem Reis.", price: 9.9, allergens: "5, 7, A1, K", tags: [], image: logoImage },
  { id: "200", code: "200", category: "Desserts", name: "Japanische Mochi", description: "Matcha und Maracuja-Geschmack, 2 Stück.", price: 5.0, allergens: "7", tags: ["vegetarisch"], image: logoImage },
  { id: "201", code: "201", category: "Desserts", name: "Banane & Mochi", description: "Gebackene Bananen und Mochi.", price: 6.0, allergens: "11, G", tags: ["vegetarisch"], image: logoImage },
  { id: "G1", code: "G1", category: "Getränke", name: "Coca Cola 0,4 l", description: "Softgetränk.", price: 4.0, allergens: "1, 11", tags: [], image: logoImage },
  { id: "G2", code: "G2", category: "Getränke", name: "Lychee Bangkok", description: "Lychee, Limetten und Soda.", price: 5.9, allergens: "", tags: ["beliebt"], image: logoImage },
  { id: "G3", code: "G3", category: "Getränke", name: "Matcha Kokos", description: "Matcha, Kokoswasser und Kondensmilch.", price: 5.3, allergens: "11, G", tags: [], image: logoImage },
  { id: "G4", code: "G4", category: "Getränke", name: "Jasmintee", description: "Traditioneller Tee.", price: 4.5, allergens: "", tags: [], image: logoImage }
];
